core/urls.py
from django.contrib import admin
from django.conf import settings

# i18n before include
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include, re_path
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path(_('admin/'), admin.site.urls),
    path('', include('lang_fr.urls', namespace='lang_fr')),
]
# adding i18n
urlpatterns += i18n_patterns(
    path('', include('lang.urls', namespace='lang')),
)

# adding rossetta
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

lang/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext as _

app_name = 'lang'

urlpatterns = [
    path('', views.home, name='home'),
    path(_('item/'), views.item, name='item'),
]

lang_fr/urls.py
from django.urls import path
from . import views

app_name = 'lang_fr'
urlpatterns = [
    path('french/', views.french, name='french'),
    path('elsefrench/', views.elsefrench, name='elsefrench'),
]

lang/models.py
from django.db import models

lang_fr/models.py
from django.db import models

# Create your models here.

lang/views.py
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext

# using getext as _
def home(request):
    trans = _('hello')
    # using translate func
    # trans = translate(language = 'fr')
    return render(request, 'lang/home.html', {'trans': trans})

def item(request):
    return render(request, 'lang/item.html')

# # translate words
# def translate(language):
#     cur_language = get_language()
#     try:
#         activate(language)
#         text = gettext('hello')
#     finally:
#         activate(cur_language)
#     return text

lang_fr/views.py
from django.shortcuts import render
from django.utils.translation import activate, gettext as _

def french(request):
    # translate in french
    activate('fr')
    transl = _('hello')
    transl2 = _("In this Python Django tutorial I will take you through the basics of setting up internationalization in Django so that you your.")
    transl3 = _("Python Django - Multiple Languages - Internationalization - Part 1")
    return render(request, 'lang_fr/french.html', {
        'transl':transl,
        'transl2':transl2,
        'transl3':transl3,
        })

def elsefrench(request):
    transl = _('hello')
    transl2 = _("In this Python Django tutorial I will take you through the basics of setting up internationalization in Django so that you your.")
    transl3 = _("Python Django - Multiple Languages - Internationalization - Part 1")
    return render(request, 'lang_fr/elsefrench.html', {
        'transl':transl,
        'transl2':transl2,
        'transl3':transl3,
        })

lang/templates/lang/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% translate 'hello' %}</title>
  </head>
  <body>
   {% include "lang/navbar.html" %}
        {% block content %}
          
        {% endblock content %}
     

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

lang/templates/lang/home.html
{% extends 'lang/base.html' %}

{% load i18n %}


{% block content %}
 
    <div class="container">
      <h2>You are in home page</h2>
      <p>When you select the language from any menu items, you should be redirected to domain_name/en/ browser(in development: http://127.0.0.1:8000/en/). This is becouse 'en' is the default language.</p>
      <!-- content -->
      {% translate 'Hello, ' %}
      {{ trans }}
      <br>
      <!-- article one -->
      {% translate 'In this Python Django tutorial I will take you through the basics of setting up internationalization in Django so that you your.' %}
      <!-- ./end -->
    </div>
    
{% endblock content %}
  

lang/templates/lang/item.html
{% extends 'lang/base.html' %}

{% load i18n %}


{% block content %}
 
    <div class="container">
      <!-- content -->
      {% translate 'hello' %}
      <br>
      <p>
        {% translate 'Python Django - Multiple Languages - Internationalization - Part 1' %}
      </p>
      <!-- ./end -->
    </div>
    
{% endblock content %}

lang/templates/lang/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a
              class="nav-link"
              aria-current="page"
              href=" {% url 'lang:home' %} "
              >{% translate 'home' %}</a
            >
          </li>
          <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href=" {% url 'lang:item' %} "
                >{% translate 'item' %}</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href=" {% url 'lang_fr:french' %} "
                >{% translate 'french' %}</a
              >
            </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              {% translate 'Language'%}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% get_current_language as LANGUAGE_CODE %}
              <!--  -->
              {% get_available_languages as LANGUAGES %}
              <!--  -->
              {% get_language_info_list for LANGUAGES as languages %}
              <!--  -->

              {% for lang in languages %}
              <li>
                <a class="dropdown-item" href="/{{ lang.code }}/">
                  {{ lang.name_local }}
                </a>
              </li>
              {% endfor %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

lang_fr/templates/lang_fr/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% translate 'hello' %}</title>
  </head>
  <body>
   {% include "lang_fr/navbar.html" %}
        {% block content %}
          
        {% endblock content %}
     

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

lang_fr/templates/lang_fr/elsefrench.html
{% extends 'lang_fr/base.html' %}

{% load i18n %}

    {% block content %}
      <div class="container">

          <h1>Translate in french</h1>
          <p>Application name: lang_fr</p>
          <p>Look! A simple translation example
              <ul>
                  <li>Case one - in views.py: import activate() and gettext()</li>
                  <li>Case two - in template: load i18n, use language tag to activate franch language, and use translate tag</li>
                </ul>
            </p>
            <h2>Case one: french is activated in views.py</h2>
            <p>Translation done in views.py:</p>
            <p>
                <br>
                {{transl}}
                <br>
                {{ transl2 }}
        <br>
        {{transl3}}
    </p>
    <h2>Case two</h2>
    <p>Translation done in template. Two cases are used also:
        <ul>
            <li>first: get_current_language as LANGUAGE_CODE </li>
            <li>second: activate french - language 'fr' and endlanguage</li>
        </ul>
    </p>
<h4>First case</h4>
<p>From french to current language:
    <!-- get corrent language -->
    {% get_current_language as LANGUAGE_CODE %}
    <br>
    <!-- Current language: {{ LANGUAGE_CODE }} -->
    Language code: {{ LANGUAGE_CODE }}
    <br>Texts is in english. It is translated from english in french in locale/en/django.po:
    <br> {% translate "Get started with Django" %}</p>
    <br> Texts is in english. It is translated from english in french in locale/fr/django.po:
    <br> {% translate "In this Python Django tutorial I will take you through the basics of setting up internationalization in Django so that you your." %}</p>
    <br> Text is in french. It is translated from english in french in locale/fr/django.po. Translation is done in wies.py, activating french language: 
    <br>{% translate "Dans ce didacticiel Python Django, je vais vous expliquer les bases de la configuration de l'internationalisation dans Django afin que vous utilisiez votre." %}</p>

    <hr>
    <hr>
    <h4>Second case: french is activated using language tag</h4>
    <!-- activate french lanuage -->
    {% language 'fr' %}
    
    {% get_current_language as LANGUAGE_CODE %}
    <br>
    <!-- Current language: {{ LANGUAGE_CODE }} -->
    Language code: {{ LANGUAGE_CODE }}
    <br>Texts is in english. It is translated from english in french in locale/en/django.po:
    <br> {% translate "Get started with Django" %}</p>
    <br> Texts is in english. It is translated from english in french in locale/fr/django.po:
    <br> {% translate "In this Python Django tutorial I will take you through the basics of setting up internationalization in Django so that you your." %}</p>
    <br> Text is in french. It is translated from english in french in locale/fr/django.po. Translation is done in wies.py, activating french language: 
    <br>{% translate "Dans ce didacticiel Python Django, je vais vous expliquer les bases de la configuration de l'internationalisation dans Django afin que vous utilisiez votre." %}</p>
    {% endlanguage %}
    
    {% endblock content %}
</div>

lang_fr/templates/lang_fr/french.html
{% extends 'lang_fr/base.html' %}

{% load i18n %}

    {% block content %}
      <div class="container">

          <h1>Translate in french</h1>
          <p>Application name: lang_fr</p>
          <p>Look! A simple translation example
              <ul>
                  <li>Case one - in views.py: import activate() and gettext()</li>
                  <li>Case two - in template: load i18n, use language tag to activate franch language, and use translate tag</li>
                </ul>
            </p>
            <h2>Case one: french is activated in views.py</h2>
            <p>Translation done in views.py:</p>
            <p>
                <br>
                {{transl}}
                <br>
                {{ transl2 }}
        <br>
        {{transl3}}
    </p>
    <h2>Case two</h2>
    <p>Translation done in template. Two cases are used also:
        <ul>
            <li>first: get_current_language as LANGUAGE_CODE </li>
            <li>second: activate french - language 'fr' and endlanguage</li>
        </ul>
    </p>
<h4>First case</h4>
<!-- get corrent language -->
{% get_current_language as LANGUAGE_CODE %}
<!-- Current language: {{ LANGUAGE_CODE }} -->
<p>Language code: {{ LANGUAGE_CODE }}</p>
<p>From french to current language:
    {% get_current_language as LANGUAGE_CODE %}
    <br>
    <!-- Current language: {{ LANGUAGE_CODE }} -->
    Language code: {{ LANGUAGE_CODE }}
    <br>Texts is in english. It is translated from english in french in locale/en/django.po:
    <br> {% translate "Get started with Django" %}</p>
    <br> Texts is in english. It is translated from english in french in locale/fr/django.po:
    <br> {% translate "In this Python Django tutorial I will take you through the basics of setting up internationalization in Django so that you your." %}</p>
    <br> Text is in french. It is translated from english in french in locale/fr/django.po. Translation is done in wies.py, activating french language: 
    <br>{% translate "Dans ce didacticiel Python Django, je vais vous expliquer les bases de la configuration de l'internationalisation dans Django afin que vous utilisiez votre." %}</p>
    <h4>Second case: french is activated using language tag</h4>
    <!-- activate franch lanuage -->
    {% language 'fr' %}
    <br>Text is in french. It is translated from english in french in locale/fr/django.po:
    <p>{% translate "In this Python Django tutorial I will take you through the basics of setting up internationalization in Django so that you your." %}</p>
    {% endlanguage %}
    
    {% endblock content %}
</div>

lang_fr/templates/lang_fr/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a
              class="nav-link"
              aria-current="page"
              href=" {% url 'lang:home' %} "
              >{% translate 'home' %}</a
            >
          </li>
          <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href=" {% url 'lang:item' %} "
                >{% translate 'item' %}</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                aria-current="page"
                href=" {% url 'lang_fr:french' %} "
                >{% translate 'french' %}</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                {% translate 'Language'%}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% get_current_language as LANGUAGE_CODE %}
                <!--  -->
                {% get_available_languages as LANGUAGES %}
                <!--  -->
                {% get_language_info_list for LANGUAGES as languages %}
                <!--  -->
  
                {% for lang in languages %}
                <li>
                  <a class="dropdown-item" href="/{{ lang.code }}/">
                    {{ lang.name_local }}
                  </a>
                </li>
                {% endfor %}
              </ul>
            </li>
        </ul>
      </div>
    </div>
  </nav>